#!/usr/bin/env python3
"""
Test enhanced server error handling for infrastructure issues.
"""
import sys
from pathlib import Path

# Add project root to Python path
PROJECT_ROOT = Path(__file__).parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.core.llm.providers.litellm_provider import LiteLLMProvider
from src.core.llm.base_llm import LLMConfig

def test_server_error_handling():
    """Test that server infrastructure errors are handled properly."""
    print("🧪 Testing Enhanced Server Error Handling...")
    print("=" * 60)

    try:
        # Create a mock LiteLLM provider
        config = LLMConfig(model="deepseek-chat", timeout=10)
        provider = LiteLLMProvider(config)

        print("✅ Created LiteLLM provider")

        # Test different types of server errors
        test_errors = [
            {
                "name": "504 Gateway Timeout (CloudFront)",
                "error_message": """Timeout Error: DeepseekException - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>
<H1>504 Gateway Timeout ERROR</H1>
<H2>The request could not be satisfied.</H2>
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later.
Generated by cloudfront (CloudFront) HTTP3 Server</BODY></HTML>"""
            },
            {
                "name": "Connection Error",
                "error_message": "Connection error: Unable to connect to deepseek.com"
            },
            {
                "name": "502 Bad Gateway",
                "error_message": "502 Bad Gateway: The server received an invalid response"
            },
            {
                "name": "Network DNS Error",
                "error_message": "Network error: DNS resolution failed for api.deepseek.com"
            },
            {
                "name": "Regular Timeout",
                "error_message": "Request timeout after 30 seconds"
            }
        ]

        print("\n🔍 Testing error message generation:")
        print("-" * 50)

        for i, test_case in enumerate(test_errors, 1):
            print(f"\n{i}. {test_case['name']}")
            print(f"   Error: {test_case['error_message'][:80]}...")

            try:
                # Create a mock exception with the error message
                class MockException(Exception):
                    def __str__(self):
                        return test_case['error_message']

                # Test the error handling
                handled_error = provider._handle_litellm_error(MockException())

                print(f"   📝 Generated message:")
                # Show first few lines of the generated error message
                error_lines = str(handled_error).split('\n')[:3]
                for line in error_lines:
                    if line.strip():
                        print(f"      {line.strip()}")

                # Check if it contains helpful suggestions
                error_text = str(handled_error).lower()
                has_model_switch = '/model' in error_text or 'switch' in error_text
                has_retry_advice = 'retry' in error_text or 'try again' in error_text
                has_status_check = 'status' in error_text or 'platform' in error_text

                if has_model_switch and has_retry_advice:
                    print(f"   ✅ Contains helpful guidance (model switch + retry advice)")
                else:
                    print(f"   ⚠️ Missing some guidance elements")

            except Exception as e:
                print(f"   ❌ Error testing: {e}")

        print("\n" + "=" * 60)
        print("✅ Server error handling test completed!")

        # Test the specific CloudFront error that the user encountered
        print(f"\n🎯 Testing actual user error:")
        print("-" * 30)

        user_error = """Timeout Error: DeepseekException - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>504 Gateway Timeout ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
Generated by cloudfront (CloudFront) HTTP3 Server</BODY></HTML>"""

        class UserException(Exception):
            def __str__(self):
                return user_error

        handled_user_error = provider._handle_litellm_error(UserException())
        print("User error response:")
        print("-" * 30)
        print(str(handled_user_error)[:400] + "..." if len(str(handled_user_error)) > 400 else str(handled_user_error))

    except Exception as e:
        print(f"❌ Error during testing: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    test_server_error_handling()